# Generated by Django 3.0.3 on 2020-02-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapGallery',
            fields=[
                ('key', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
