# Generated by Django 3.0.2 on 2020-02-21 15:47

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        CITextExtension(),
    ]
