# Generated by Django 3.0.3 on 2020-02-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaps', to='galleries.SnapGallery')),
            ],
        ),
    ]
